// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: budget.proto
#ifndef GRPC_budget_2eproto__INCLUDED
#define GRPC_budget_2eproto__INCLUDED

#include "budget.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

class BudgetInfo final {
 public:
  static constexpr char const* service_full_name() {
    return "BudgetInfo";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::BudgetSplit* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BudgetSplit>> AsyncGetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BudgetSplit>>(AsyncGetBudgetSplitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BudgetSplit>> PrepareAsyncGetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::BudgetSplit>>(PrepareAsyncGetBudgetSplitRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest* request, ::BudgetSplit* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest* request, ::BudgetSplit* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BudgetSplit>* AsyncGetBudgetSplitRaw(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::BudgetSplit>* PrepareAsyncGetBudgetSplitRaw(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::BudgetSplit* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BudgetSplit>> AsyncGetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BudgetSplit>>(AsyncGetBudgetSplitRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BudgetSplit>> PrepareAsyncGetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::BudgetSplit>>(PrepareAsyncGetBudgetSplitRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest* request, ::BudgetSplit* response, std::function<void(::grpc::Status)>) override;
      void GetBudgetSplit(::grpc::ClientContext* context, const ::BudgetSplitRequest* request, ::BudgetSplit* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::BudgetSplit>* AsyncGetBudgetSplitRaw(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::BudgetSplit>* PrepareAsyncGetBudgetSplitRaw(::grpc::ClientContext* context, const ::BudgetSplitRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetBudgetSplit_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetBudgetSplit(::grpc::ServerContext* context, const ::BudgetSplitRequest* request, ::BudgetSplit* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetBudgetSplit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetBudgetSplit() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetBudgetSplit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBudgetSplit(::grpc::ServerContext* /*context*/, const ::BudgetSplitRequest* /*request*/, ::BudgetSplit* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBudgetSplit(::grpc::ServerContext* context, ::BudgetSplitRequest* request, ::grpc::ServerAsyncResponseWriter< ::BudgetSplit>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetBudgetSplit<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetBudgetSplit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetBudgetSplit() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::BudgetSplitRequest, ::BudgetSplit>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::BudgetSplitRequest* request, ::BudgetSplit* response) { return this->GetBudgetSplit(context, request, response); }));}
    void SetMessageAllocatorFor_GetBudgetSplit(
        ::grpc::MessageAllocator< ::BudgetSplitRequest, ::BudgetSplit>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::BudgetSplitRequest, ::BudgetSplit>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetBudgetSplit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBudgetSplit(::grpc::ServerContext* /*context*/, const ::BudgetSplitRequest* /*request*/, ::BudgetSplit* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBudgetSplit(
      ::grpc::CallbackServerContext* /*context*/, const ::BudgetSplitRequest* /*request*/, ::BudgetSplit* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetBudgetSplit<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetBudgetSplit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetBudgetSplit() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetBudgetSplit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBudgetSplit(::grpc::ServerContext* /*context*/, const ::BudgetSplitRequest* /*request*/, ::BudgetSplit* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetBudgetSplit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetBudgetSplit() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetBudgetSplit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBudgetSplit(::grpc::ServerContext* /*context*/, const ::BudgetSplitRequest* /*request*/, ::BudgetSplit* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetBudgetSplit(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetBudgetSplit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetBudgetSplit() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetBudgetSplit(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetBudgetSplit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetBudgetSplit(::grpc::ServerContext* /*context*/, const ::BudgetSplitRequest* /*request*/, ::BudgetSplit* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetBudgetSplit(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetBudgetSplit : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetBudgetSplit() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::BudgetSplitRequest, ::BudgetSplit>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::BudgetSplitRequest, ::BudgetSplit>* streamer) {
                       return this->StreamedGetBudgetSplit(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetBudgetSplit() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetBudgetSplit(::grpc::ServerContext* /*context*/, const ::BudgetSplitRequest* /*request*/, ::BudgetSplit* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetBudgetSplit(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::BudgetSplitRequest,::BudgetSplit>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetBudgetSplit<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetBudgetSplit<Service > StreamedService;
};


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_budget_2eproto__INCLUDED
