// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: budget.proto
// Protobuf C++ Version: 6.30.1

#ifndef budget_2eproto_2epb_2eh
#define budget_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6030001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_budget_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_budget_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_budget_2eproto;
}  // extern "C"
class BudgetSplit;
struct BudgetSplitDefaultTypeInternal;
extern BudgetSplitDefaultTypeInternal _BudgetSplit_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BudgetSplit_class_data_;
class BudgetSplitRequest;
struct BudgetSplitRequestDefaultTypeInternal;
extern BudgetSplitRequestDefaultTypeInternal _BudgetSplitRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull BudgetSplitRequest_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class BudgetSplitRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:BudgetSplitRequest) */ {
 public:
  inline BudgetSplitRequest() : BudgetSplitRequest(nullptr) {}
  ~BudgetSplitRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BudgetSplitRequest* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BudgetSplitRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BudgetSplitRequest(::google::protobuf::internal::ConstantInitialized);

  inline BudgetSplitRequest(const BudgetSplitRequest& from) : BudgetSplitRequest(nullptr, from) {}
  inline BudgetSplitRequest(BudgetSplitRequest&& from) noexcept
      : BudgetSplitRequest(nullptr, std::move(from)) {}
  inline BudgetSplitRequest& operator=(const BudgetSplitRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline BudgetSplitRequest& operator=(BudgetSplitRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BudgetSplitRequest& default_instance() {
    return *reinterpret_cast<const BudgetSplitRequest*>(
        &_BudgetSplitRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(BudgetSplitRequest& a, BudgetSplitRequest& b) { a.Swap(&b); }
  inline void Swap(BudgetSplitRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BudgetSplitRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BudgetSplitRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BudgetSplitRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BudgetSplitRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BudgetSplitRequest& from) { BudgetSplitRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BudgetSplitRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "BudgetSplitRequest"; }

 protected:
  explicit BudgetSplitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BudgetSplitRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BudgetSplitRequest& from);
  BudgetSplitRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BudgetSplitRequest&& from) noexcept
      : BudgetSplitRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWantPercentFieldNumber = 1,
    kNeedPercentFieldNumber = 2,
    kTotalIncomeFieldNumber = 3,
    kTaxesFieldNumber = 4,
  };
  // float want_percent = 1;
  void clear_want_percent() ;
  float want_percent() const;
  void set_want_percent(float value);

  private:
  float _internal_want_percent() const;
  void _internal_set_want_percent(float value);

  public:
  // float need_percent = 2;
  void clear_need_percent() ;
  float need_percent() const;
  void set_need_percent(float value);

  private:
  float _internal_need_percent() const;
  void _internal_set_need_percent(float value);

  public:
  // double total_income = 3;
  void clear_total_income() ;
  double total_income() const;
  void set_total_income(double value);

  private:
  double _internal_total_income() const;
  void _internal_set_total_income(double value);

  public:
  // bool taxes = 4;
  void clear_taxes() ;
  bool taxes() const;
  void set_taxes(bool value);

  private:
  bool _internal_taxes() const;
  void _internal_set_taxes(bool value);

  public:
  // @@protoc_insertion_point(class_scope:BudgetSplitRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BudgetSplitRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float want_percent_;
    float need_percent_;
    double total_income_;
    bool taxes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_budget_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BudgetSplitRequest_class_data_;
// -------------------------------------------------------------------

class BudgetSplit final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:BudgetSplit) */ {
 public:
  inline BudgetSplit() : BudgetSplit(nullptr) {}
  ~BudgetSplit() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BudgetSplit* PROTOBUF_NONNULL msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BudgetSplit));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BudgetSplit(::google::protobuf::internal::ConstantInitialized);

  inline BudgetSplit(const BudgetSplit& from) : BudgetSplit(nullptr, from) {}
  inline BudgetSplit(BudgetSplit&& from) noexcept
      : BudgetSplit(nullptr, std::move(from)) {}
  inline BudgetSplit& operator=(const BudgetSplit& from) {
    CopyFrom(from);
    return *this;
  }
  inline BudgetSplit& operator=(BudgetSplit&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BudgetSplit& default_instance() {
    return *reinterpret_cast<const BudgetSplit*>(
        &_BudgetSplit_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(BudgetSplit& a, BudgetSplit& b) { a.Swap(&b); }
  inline void Swap(BudgetSplit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BudgetSplit* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BudgetSplit* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BudgetSplit>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BudgetSplit& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BudgetSplit& from) { BudgetSplit::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BudgetSplit* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "BudgetSplit"; }

 protected:
  explicit BudgetSplit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  BudgetSplit(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const BudgetSplit& from);
  BudgetSplit(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, BudgetSplit&& from) noexcept
      : BudgetSplit(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kWantsFieldNumber = 1,
    kNeedsFieldNumber = 2,
    kSavingsFieldNumber = 3,
    kTaxesFieldNumber = 4,
  };
  // float wants = 1;
  void clear_wants() ;
  float wants() const;
  void set_wants(float value);

  private:
  float _internal_wants() const;
  void _internal_set_wants(float value);

  public:
  // float needs = 2;
  void clear_needs() ;
  float needs() const;
  void set_needs(float value);

  private:
  float _internal_needs() const;
  void _internal_set_needs(float value);

  public:
  // float savings = 3;
  void clear_savings() ;
  float savings() const;
  void set_savings(float value);

  private:
  float _internal_savings() const;
  void _internal_set_savings(float value);

  public:
  // float taxes = 4;
  void clear_taxes() ;
  float taxes() const;
  void set_taxes(float value);

  private:
  float _internal_taxes() const;
  void _internal_set_taxes(float value);

  public:
  // @@protoc_insertion_point(class_scope:BudgetSplit)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const BudgetSplit& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    float wants_;
    float needs_;
    float savings_;
    float taxes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_budget_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull BudgetSplit_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// BudgetSplitRequest

// float want_percent = 1;
inline void BudgetSplitRequest::clear_want_percent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.want_percent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float BudgetSplitRequest::want_percent() const {
  // @@protoc_insertion_point(field_get:BudgetSplitRequest.want_percent)
  return _internal_want_percent();
}
inline void BudgetSplitRequest::set_want_percent(float value) {
  _internal_set_want_percent(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:BudgetSplitRequest.want_percent)
}
inline float BudgetSplitRequest::_internal_want_percent() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.want_percent_;
}
inline void BudgetSplitRequest::_internal_set_want_percent(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.want_percent_ = value;
}

// float need_percent = 2;
inline void BudgetSplitRequest::clear_need_percent() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.need_percent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float BudgetSplitRequest::need_percent() const {
  // @@protoc_insertion_point(field_get:BudgetSplitRequest.need_percent)
  return _internal_need_percent();
}
inline void BudgetSplitRequest::set_need_percent(float value) {
  _internal_set_need_percent(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:BudgetSplitRequest.need_percent)
}
inline float BudgetSplitRequest::_internal_need_percent() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.need_percent_;
}
inline void BudgetSplitRequest::_internal_set_need_percent(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.need_percent_ = value;
}

// double total_income = 3;
inline void BudgetSplitRequest::clear_total_income() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_income_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline double BudgetSplitRequest::total_income() const {
  // @@protoc_insertion_point(field_get:BudgetSplitRequest.total_income)
  return _internal_total_income();
}
inline void BudgetSplitRequest::set_total_income(double value) {
  _internal_set_total_income(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:BudgetSplitRequest.total_income)
}
inline double BudgetSplitRequest::_internal_total_income() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.total_income_;
}
inline void BudgetSplitRequest::_internal_set_total_income(double value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.total_income_ = value;
}

// bool taxes = 4;
inline void BudgetSplitRequest::clear_taxes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.taxes_ = false;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline bool BudgetSplitRequest::taxes() const {
  // @@protoc_insertion_point(field_get:BudgetSplitRequest.taxes)
  return _internal_taxes();
}
inline void BudgetSplitRequest::set_taxes(bool value) {
  _internal_set_taxes(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:BudgetSplitRequest.taxes)
}
inline bool BudgetSplitRequest::_internal_taxes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.taxes_;
}
inline void BudgetSplitRequest::_internal_set_taxes(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.taxes_ = value;
}

// -------------------------------------------------------------------

// BudgetSplit

// float wants = 1;
inline void BudgetSplit::clear_wants() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wants_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float BudgetSplit::wants() const {
  // @@protoc_insertion_point(field_get:BudgetSplit.wants)
  return _internal_wants();
}
inline void BudgetSplit::set_wants(float value) {
  _internal_set_wants(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:BudgetSplit.wants)
}
inline float BudgetSplit::_internal_wants() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.wants_;
}
inline void BudgetSplit::_internal_set_wants(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.wants_ = value;
}

// float needs = 2;
inline void BudgetSplit::clear_needs() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.needs_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline float BudgetSplit::needs() const {
  // @@protoc_insertion_point(field_get:BudgetSplit.needs)
  return _internal_needs();
}
inline void BudgetSplit::set_needs(float value) {
  _internal_set_needs(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:BudgetSplit.needs)
}
inline float BudgetSplit::_internal_needs() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.needs_;
}
inline void BudgetSplit::_internal_set_needs(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.needs_ = value;
}

// float savings = 3;
inline void BudgetSplit::clear_savings() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.savings_ = 0;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline float BudgetSplit::savings() const {
  // @@protoc_insertion_point(field_get:BudgetSplit.savings)
  return _internal_savings();
}
inline void BudgetSplit::set_savings(float value) {
  _internal_set_savings(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:BudgetSplit.savings)
}
inline float BudgetSplit::_internal_savings() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.savings_;
}
inline void BudgetSplit::_internal_set_savings(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.savings_ = value;
}

// float taxes = 4;
inline void BudgetSplit::clear_taxes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.taxes_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float BudgetSplit::taxes() const {
  // @@protoc_insertion_point(field_get:BudgetSplit.taxes)
  return _internal_taxes();
}
inline void BudgetSplit::set_taxes(float value) {
  _internal_set_taxes(value);
  _impl_._has_bits_[0] |= 0x00000008u;
  // @@protoc_insertion_point(field_set:BudgetSplit.taxes)
}
inline float BudgetSplit::_internal_taxes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.taxes_;
}
inline void BudgetSplit::_internal_set_taxes(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.taxes_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // budget_2eproto_2epb_2eh
